name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

# Минимально необходимые права для чтения репо
permissions:
  contents: read

# Отменять предыдущие запуски на той же ветке/PR
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Make gradlew executable
        run: |
          test -f gradlew || (echo "gradlew not found" && exit 1)
          chmod +x gradlew
          ls -l gradlew

      - name: Build & Test
        run: sh ./gradlew --no-daemon clean check

      - name: Build & Test (no secrets)
        run: ./gradlew --no-daemon clean check

      # Опционально запускаем gradle-гарды, если они определены в сборке
      - name: Run Gradle guards if present
        run: |
          ./gradlew --no-daemon tasks --all > tasks.txt
          if grep -q "verifyNoBin" tasks.txt; then ./gradlew --no-daemon verifyNoBin; fi
          if grep -q "assertNoBinInJar" tasks.txt; then ./gradlew --no-daemon assertNoBinInJar; fi

      # Публикация отчетов при падении (необязательно)
      - name: Upload Test Reports (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/test
            **/build/test-results/test
