name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

# Минимально необходимые права для чтения репо
permissions:
  contents: read

# Отменять предыдущие запуски на той же ветке/PR
concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Build & Test
        run: sh ./gradlew --no-daemon clean check

      # Генерация отчётов покрытия (не влияет на прохождение тестов)
      - name: Coverage Report (Jacoco)
        run: sh ./gradlew --no-daemon jacocoTestReport

      - name: Upload Coverage Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: |
            **/build/reports/jacoco/test/html
            **/build/reports/jacoco/test/jacocoTestReport.xml
