name: Guard: ban *.bin in VCS

on:
  pull_request:
  push:

permissions:
  contents: read

jobs:
  guard-bin:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: changes
        uses: tj-actions/changed-files@v45

      - name: Fail on banned *.bin
        run: |
          hits=""
          for f in ${{ steps.changes.outputs.all_changed_files }}; do
            if echo "$f" | grep -Ei '\\.bin$' > /dev/null; then
              hits="${hits}\n - ${f}"
            fi
          done
          if [ -n "$hits" ]; then
            echo "::error::Banned binary files detected:${hits}"
            exit 1
          fi
